name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Financer system
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - Ensyferum

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature request is not already covered by existing functionality
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Config Server
        - Eureka Server
        - API Gateway
        - Account Service
        - Common Library
        - Eureka Integration
        - Infrastructure (Docker/Database)
        - Build System (Maven)
        - CI/CD Pipeline
        - Documentation
        - New Component/Service
        - Cross-cutting (Multiple Components)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking other work)
        - High (Important for next release)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current pain point?
      placeholder: |
        As a [user type], I want [goal] so that [benefit].
        
        Currently, when I [current behavior], I experience [pain point].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions you've considered
      placeholder: Describe alternative approaches...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Improved performance
        - Better user experience
        - Reduced complexity
        - etc.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Implementation Details
      description: If you have ideas about how this could be implemented technically
      placeholder: |
        - API changes needed
        - Database schema changes
        - New dependencies
        - Configuration changes
        - etc.

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups or wireframes to illustrate your idea
      placeholder: Drag and drop images here...

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No - Backward compatible"
        - "Yes - Breaking change"
        - "Maybe - Needs investigation"
    validations:
      required: true

  - type: textarea
    id: migration-plan
    attributes:
      label: Migration Plan
      description: If this is a breaking change, how would existing users migrate?
      placeholder: Describe the migration path for existing users...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing and validation
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples about the feature request here
      placeholder: |
        - Related issues
        - External references
        - Examples from other projects
        - etc.