# Configuração para o Account Service

server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/financer_accounts
    username: financer_user
    password: financer123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.financer: INFO
    org.springframework.cloud.config: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [ACCOUNT-SERVICE] [%level] [%logger{36}] - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://financer-postgres:5432/financer_accounts
eureka:
  client:
    service-url:
      defaultZone: http://financer-eureka-server:8761/eureka/
  instance:
    hostname: account-service
    prefer-ip-address: false