# Configuração específica para o Eureka Server

server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 30000
    renewal-threshold-update-interval-ms: 15000
    expected-client-renewal-interval-seconds: 30
    renewal-percent-threshold: 0.49
    response-cache-auto-expiration-in-seconds: 180
    response-cache-update-interval-ms: 30000
  dashboard:
    enabled: true
    path: /

# Enhanced Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,eureka,shutdown
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    eureka:
      enabled: true
    shutdown:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: false

# Enhanced Logging for Service Discovery
logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.financer: DEBUG
  file:
    path: /app/logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [EUREKA-SERVER] %logger{36} - %msg%n"