# Transaction Service - Docker Profile Configuration

server:
  port: 8082

spring:
  application:
    name: transaction-service
  
  # MongoDB configuration for Docker
  data:
    mongodb:
      uri: mongodb://orchestration_service:orchestration123@financer-mongodb:27017/financer
      auto-index-creation: true
  
  # PostgreSQL configuration for Docker  
  datasource:
    url: jdbc:postgresql://financer-postgres:5432/financer
    username: transaction_service
    password: transaction123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: transaction_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

# Eureka Discovery Configuration
eureka:
  client:
    service-url:
      defaultZone: http://financer-eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# Configurações específicas do domínio
financer:
  transaction:
    validation:
      max-amount: 1000000.00
      require-description: true
    processing:
      async-enabled: true
      batch-size: 100
    audit:
      enabled: true

# Logging
logging:
  level:
    com.financer: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.jpa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"